/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedDataBrowserRouteImport } from './routes/_authenticated/data.browser'
import { Route as AuthenticatedDataJournalsRouteImport } from './routes/_authenticated/data.journals'
import { Route as AuthenticatedDataUploadRouteImport } from './routes/_authenticated/data.upload'
import { Route as AuthenticatedProcessMonitorRouteImport } from './routes/_authenticated/process.monitor'
import { Route as AuthenticatedProcessTaskLogRouteImport } from './routes/_authenticated/process.task-log'
import { Route as AuthenticatedProcessWorkflowTemplatesRouteImport } from './routes/_authenticated/process.workflow-templates'
import { Route as AuthenticatedReportsAuditTrailRouteImport } from './routes/_authenticated/reports.audit-trail'
import { Route as AuthenticatedReportsConsolidatedStatementsRouteImport } from './routes/_authenticated/reports.consolidated-statements'
import { Route as AuthenticatedReportsIcReconciliationRouteImport } from './routes/_authenticated/reports.ic-reconciliation'
import { Route as AuthenticatedReportsTrialBalanceRouteImport } from './routes/_authenticated/reports.trial-balance'
import { Route as AuthenticatedRulesBalanceCarryForwardRouteImport } from './routes/_authenticated/rules.balance-carry-forward'
import { Route as AuthenticatedRulesConsolidationOfInvestmentsRouteImport } from './routes/_authenticated/rules.consolidation-of-investments'
import { Route as AuthenticatedRulesCurrencyTranslationRouteImport } from './routes/_authenticated/rules.currency-translation'
import { Route as AuthenticatedRulesIcEliminationRouteImport } from './routes/_authenticated/rules.ic-elimination'
import { Route as AuthenticatedRulesNetIncomeRouteImport } from './routes/_authenticated/rules.net-income'
import { Route as AuthenticatedSetupConsGroupsRouteImport } from './routes/_authenticated/setup.cons-groups'
import { Route as AuthenticatedSetupDataModelRouteImport } from './routes/_authenticated/setup.data-model'
import { Route as AuthenticatedSetupDimensionsRouteImport } from './routes/_authenticated/setup.dimensions'
import { Route as AuthenticatedSetupFxRatesRouteImport } from './routes/_authenticated/setup.fx-rates'
import { Route as AuthenticatedSetupHierarchiesRouteImport } from './routes/_authenticated/setup.hierarchies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDataBrowserRoute =
  AuthenticatedDataBrowserRouteImport.update({
    id: '/data/browser',
    path: '/data/browser',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDataJournalsRoute =
  AuthenticatedDataJournalsRouteImport.update({
    id: '/data/journals',
    path: '/data/journals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDataUploadRoute = AuthenticatedDataUploadRouteImport.update({
  id: '/data/upload',
  path: '/data/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcessMonitorRoute =
  AuthenticatedProcessMonitorRouteImport.update({
    id: '/process/monitor',
    path: '/process/monitor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcessTaskLogRoute =
  AuthenticatedProcessTaskLogRouteImport.update({
    id: '/process/task-log',
    path: '/process/task-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcessWorkflowTemplatesRoute =
  AuthenticatedProcessWorkflowTemplatesRouteImport.update({
    id: '/process/workflow-templates',
    path: '/process/workflow-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsAuditTrailRoute =
  AuthenticatedReportsAuditTrailRouteImport.update({
    id: '/reports/audit-trail',
    path: '/reports/audit-trail',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsConsolidatedStatementsRoute =
  AuthenticatedReportsConsolidatedStatementsRouteImport.update({
    id: '/reports/consolidated-statements',
    path: '/reports/consolidated-statements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIcReconciliationRoute =
  AuthenticatedReportsIcReconciliationRouteImport.update({
    id: '/reports/ic-reconciliation',
    path: '/reports/ic-reconciliation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsTrialBalanceRoute =
  AuthenticatedReportsTrialBalanceRouteImport.update({
    id: '/reports/trial-balance',
    path: '/reports/trial-balance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRulesBalanceCarryForwardRoute =
  AuthenticatedRulesBalanceCarryForwardRouteImport.update({
    id: '/rules/balance-carry-forward',
    path: '/rules/balance-carry-forward',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRulesConsolidationOfInvestmentsRoute =
  AuthenticatedRulesConsolidationOfInvestmentsRouteImport.update({
    id: '/rules/consolidation-of-investments',
    path: '/rules/consolidation-of-investments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRulesCurrencyTranslationRoute =
  AuthenticatedRulesCurrencyTranslationRouteImport.update({
    id: '/rules/currency-translation',
    path: '/rules/currency-translation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRulesIcEliminationRoute =
  AuthenticatedRulesIcEliminationRouteImport.update({
    id: '/rules/ic-elimination',
    path: '/rules/ic-elimination',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRulesNetIncomeRoute =
  AuthenticatedRulesNetIncomeRouteImport.update({
    id: '/rules/net-income',
    path: '/rules/net-income',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSetupConsGroupsRoute =
  AuthenticatedSetupConsGroupsRouteImport.update({
    id: '/setup/cons-groups',
    path: '/setup/cons-groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSetupDataModelRoute =
  AuthenticatedSetupDataModelRouteImport.update({
    id: '/setup/data-model',
    path: '/setup/data-model',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSetupDimensionsRoute =
  AuthenticatedSetupDimensionsRouteImport.update({
    id: '/setup/dimensions',
    path: '/setup/dimensions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSetupFxRatesRoute =
  AuthenticatedSetupFxRatesRouteImport.update({
    id: '/setup/fx-rates',
    path: '/setup/fx-rates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSetupHierarchiesRoute =
  AuthenticatedSetupHierarchiesRouteImport.update({
    id: '/setup/hierarchies',
    path: '/setup/hierarchies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/data/browser': typeof AuthenticatedDataBrowserRoute
  '/data/journals': typeof AuthenticatedDataJournalsRoute
  '/data/upload': typeof AuthenticatedDataUploadRoute
  '/process/monitor': typeof AuthenticatedProcessMonitorRoute
  '/process/task-log': typeof AuthenticatedProcessTaskLogRoute
  '/process/workflow-templates': typeof AuthenticatedProcessWorkflowTemplatesRoute
  '/reports/audit-trail': typeof AuthenticatedReportsAuditTrailRoute
  '/reports/consolidated-statements': typeof AuthenticatedReportsConsolidatedStatementsRoute
  '/reports/ic-reconciliation': typeof AuthenticatedReportsIcReconciliationRoute
  '/reports/trial-balance': typeof AuthenticatedReportsTrialBalanceRoute
  '/rules/balance-carry-forward': typeof AuthenticatedRulesBalanceCarryForwardRoute
  '/rules/consolidation-of-investments': typeof AuthenticatedRulesConsolidationOfInvestmentsRoute
  '/rules/currency-translation': typeof AuthenticatedRulesCurrencyTranslationRoute
  '/rules/ic-elimination': typeof AuthenticatedRulesIcEliminationRoute
  '/rules/net-income': typeof AuthenticatedRulesNetIncomeRoute
  '/setup/cons-groups': typeof AuthenticatedSetupConsGroupsRoute
  '/setup/data-model': typeof AuthenticatedSetupDataModelRoute
  '/setup/dimensions': typeof AuthenticatedSetupDimensionsRoute
  '/setup/fx-rates': typeof AuthenticatedSetupFxRatesRoute
  '/setup/hierarchies': typeof AuthenticatedSetupHierarchiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/data/browser': typeof AuthenticatedDataBrowserRoute
  '/data/journals': typeof AuthenticatedDataJournalsRoute
  '/data/upload': typeof AuthenticatedDataUploadRoute
  '/process/monitor': typeof AuthenticatedProcessMonitorRoute
  '/process/task-log': typeof AuthenticatedProcessTaskLogRoute
  '/process/workflow-templates': typeof AuthenticatedProcessWorkflowTemplatesRoute
  '/reports/audit-trail': typeof AuthenticatedReportsAuditTrailRoute
  '/reports/consolidated-statements': typeof AuthenticatedReportsConsolidatedStatementsRoute
  '/reports/ic-reconciliation': typeof AuthenticatedReportsIcReconciliationRoute
  '/reports/trial-balance': typeof AuthenticatedReportsTrialBalanceRoute
  '/rules/balance-carry-forward': typeof AuthenticatedRulesBalanceCarryForwardRoute
  '/rules/consolidation-of-investments': typeof AuthenticatedRulesConsolidationOfInvestmentsRoute
  '/rules/currency-translation': typeof AuthenticatedRulesCurrencyTranslationRoute
  '/rules/ic-elimination': typeof AuthenticatedRulesIcEliminationRoute
  '/rules/net-income': typeof AuthenticatedRulesNetIncomeRoute
  '/setup/cons-groups': typeof AuthenticatedSetupConsGroupsRoute
  '/setup/data-model': typeof AuthenticatedSetupDataModelRoute
  '/setup/dimensions': typeof AuthenticatedSetupDimensionsRoute
  '/setup/fx-rates': typeof AuthenticatedSetupFxRatesRoute
  '/setup/hierarchies': typeof AuthenticatedSetupHierarchiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/data/browser': typeof AuthenticatedDataBrowserRoute
  '/_authenticated/data/journals': typeof AuthenticatedDataJournalsRoute
  '/_authenticated/data/upload': typeof AuthenticatedDataUploadRoute
  '/_authenticated/process/monitor': typeof AuthenticatedProcessMonitorRoute
  '/_authenticated/process/task-log': typeof AuthenticatedProcessTaskLogRoute
  '/_authenticated/process/workflow-templates': typeof AuthenticatedProcessWorkflowTemplatesRoute
  '/_authenticated/reports/audit-trail': typeof AuthenticatedReportsAuditTrailRoute
  '/_authenticated/reports/consolidated-statements': typeof AuthenticatedReportsConsolidatedStatementsRoute
  '/_authenticated/reports/ic-reconciliation': typeof AuthenticatedReportsIcReconciliationRoute
  '/_authenticated/reports/trial-balance': typeof AuthenticatedReportsTrialBalanceRoute
  '/_authenticated/rules/balance-carry-forward': typeof AuthenticatedRulesBalanceCarryForwardRoute
  '/_authenticated/rules/consolidation-of-investments': typeof AuthenticatedRulesConsolidationOfInvestmentsRoute
  '/_authenticated/rules/currency-translation': typeof AuthenticatedRulesCurrencyTranslationRoute
  '/_authenticated/rules/ic-elimination': typeof AuthenticatedRulesIcEliminationRoute
  '/_authenticated/rules/net-income': typeof AuthenticatedRulesNetIncomeRoute
  '/_authenticated/setup/cons-groups': typeof AuthenticatedSetupConsGroupsRoute
  '/_authenticated/setup/data-model': typeof AuthenticatedSetupDataModelRoute
  '/_authenticated/setup/dimensions': typeof AuthenticatedSetupDimensionsRoute
  '/_authenticated/setup/fx-rates': typeof AuthenticatedSetupFxRatesRoute
  '/_authenticated/setup/hierarchies': typeof AuthenticatedSetupHierarchiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/data/browser'
    | '/data/journals'
    | '/data/upload'
    | '/process/monitor'
    | '/process/task-log'
    | '/process/workflow-templates'
    | '/reports/audit-trail'
    | '/reports/consolidated-statements'
    | '/reports/ic-reconciliation'
    | '/reports/trial-balance'
    | '/rules/balance-carry-forward'
    | '/rules/consolidation-of-investments'
    | '/rules/currency-translation'
    | '/rules/ic-elimination'
    | '/rules/net-income'
    | '/setup/cons-groups'
    | '/setup/data-model'
    | '/setup/dimensions'
    | '/setup/fx-rates'
    | '/setup/hierarchies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/data/browser'
    | '/data/journals'
    | '/data/upload'
    | '/process/monitor'
    | '/process/task-log'
    | '/process/workflow-templates'
    | '/reports/audit-trail'
    | '/reports/consolidated-statements'
    | '/reports/ic-reconciliation'
    | '/reports/trial-balance'
    | '/rules/balance-carry-forward'
    | '/rules/consolidation-of-investments'
    | '/rules/currency-translation'
    | '/rules/ic-elimination'
    | '/rules/net-income'
    | '/setup/cons-groups'
    | '/setup/data-model'
    | '/setup/dimensions'
    | '/setup/fx-rates'
    | '/setup/hierarchies'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/data/browser'
    | '/_authenticated/data/journals'
    | '/_authenticated/data/upload'
    | '/_authenticated/process/monitor'
    | '/_authenticated/process/task-log'
    | '/_authenticated/process/workflow-templates'
    | '/_authenticated/reports/audit-trail'
    | '/_authenticated/reports/consolidated-statements'
    | '/_authenticated/reports/ic-reconciliation'
    | '/_authenticated/reports/trial-balance'
    | '/_authenticated/rules/balance-carry-forward'
    | '/_authenticated/rules/consolidation-of-investments'
    | '/_authenticated/rules/currency-translation'
    | '/_authenticated/rules/ic-elimination'
    | '/_authenticated/rules/net-income'
    | '/_authenticated/setup/cons-groups'
    | '/_authenticated/setup/data-model'
    | '/_authenticated/setup/dimensions'
    | '/_authenticated/setup/fx-rates'
    | '/_authenticated/setup/hierarchies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/data/browser': {
      id: '/_authenticated/data/browser'
      path: '/data/browser'
      fullPath: '/data/browser'
      preLoaderRoute: typeof AuthenticatedDataBrowserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data/journals': {
      id: '/_authenticated/data/journals'
      path: '/data/journals'
      fullPath: '/data/journals'
      preLoaderRoute: typeof AuthenticatedDataJournalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data/upload': {
      id: '/_authenticated/data/upload'
      path: '/data/upload'
      fullPath: '/data/upload'
      preLoaderRoute: typeof AuthenticatedDataUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/process/monitor': {
      id: '/_authenticated/process/monitor'
      path: '/process/monitor'
      fullPath: '/process/monitor'
      preLoaderRoute: typeof AuthenticatedProcessMonitorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/process/task-log': {
      id: '/_authenticated/process/task-log'
      path: '/process/task-log'
      fullPath: '/process/task-log'
      preLoaderRoute: typeof AuthenticatedProcessTaskLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/process/workflow-templates': {
      id: '/_authenticated/process/workflow-templates'
      path: '/process/workflow-templates'
      fullPath: '/process/workflow-templates'
      preLoaderRoute: typeof AuthenticatedProcessWorkflowTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/audit-trail': {
      id: '/_authenticated/reports/audit-trail'
      path: '/reports/audit-trail'
      fullPath: '/reports/audit-trail'
      preLoaderRoute: typeof AuthenticatedReportsAuditTrailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/consolidated-statements': {
      id: '/_authenticated/reports/consolidated-statements'
      path: '/reports/consolidated-statements'
      fullPath: '/reports/consolidated-statements'
      preLoaderRoute: typeof AuthenticatedReportsConsolidatedStatementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/ic-reconciliation': {
      id: '/_authenticated/reports/ic-reconciliation'
      path: '/reports/ic-reconciliation'
      fullPath: '/reports/ic-reconciliation'
      preLoaderRoute: typeof AuthenticatedReportsIcReconciliationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/trial-balance': {
      id: '/_authenticated/reports/trial-balance'
      path: '/reports/trial-balance'
      fullPath: '/reports/trial-balance'
      preLoaderRoute: typeof AuthenticatedReportsTrialBalanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rules/balance-carry-forward': {
      id: '/_authenticated/rules/balance-carry-forward'
      path: '/rules/balance-carry-forward'
      fullPath: '/rules/balance-carry-forward'
      preLoaderRoute: typeof AuthenticatedRulesBalanceCarryForwardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rules/consolidation-of-investments': {
      id: '/_authenticated/rules/consolidation-of-investments'
      path: '/rules/consolidation-of-investments'
      fullPath: '/rules/consolidation-of-investments'
      preLoaderRoute: typeof AuthenticatedRulesConsolidationOfInvestmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rules/currency-translation': {
      id: '/_authenticated/rules/currency-translation'
      path: '/rules/currency-translation'
      fullPath: '/rules/currency-translation'
      preLoaderRoute: typeof AuthenticatedRulesCurrencyTranslationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rules/ic-elimination': {
      id: '/_authenticated/rules/ic-elimination'
      path: '/rules/ic-elimination'
      fullPath: '/rules/ic-elimination'
      preLoaderRoute: typeof AuthenticatedRulesIcEliminationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rules/net-income': {
      id: '/_authenticated/rules/net-income'
      path: '/rules/net-income'
      fullPath: '/rules/net-income'
      preLoaderRoute: typeof AuthenticatedRulesNetIncomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup/cons-groups': {
      id: '/_authenticated/setup/cons-groups'
      path: '/setup/cons-groups'
      fullPath: '/setup/cons-groups'
      preLoaderRoute: typeof AuthenticatedSetupConsGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup/data-model': {
      id: '/_authenticated/setup/data-model'
      path: '/setup/data-model'
      fullPath: '/setup/data-model'
      preLoaderRoute: typeof AuthenticatedSetupDataModelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup/dimensions': {
      id: '/_authenticated/setup/dimensions'
      path: '/setup/dimensions'
      fullPath: '/setup/dimensions'
      preLoaderRoute: typeof AuthenticatedSetupDimensionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup/fx-rates': {
      id: '/_authenticated/setup/fx-rates'
      path: '/setup/fx-rates'
      fullPath: '/setup/fx-rates'
      preLoaderRoute: typeof AuthenticatedSetupFxRatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup/hierarchies': {
      id: '/_authenticated/setup/hierarchies'
      path: '/setup/hierarchies'
      fullPath: '/setup/hierarchies'
      preLoaderRoute: typeof AuthenticatedSetupHierarchiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDataBrowserRoute: typeof AuthenticatedDataBrowserRoute
  AuthenticatedDataJournalsRoute: typeof AuthenticatedDataJournalsRoute
  AuthenticatedDataUploadRoute: typeof AuthenticatedDataUploadRoute
  AuthenticatedProcessMonitorRoute: typeof AuthenticatedProcessMonitorRoute
  AuthenticatedProcessTaskLogRoute: typeof AuthenticatedProcessTaskLogRoute
  AuthenticatedProcessWorkflowTemplatesRoute: typeof AuthenticatedProcessWorkflowTemplatesRoute
  AuthenticatedReportsAuditTrailRoute: typeof AuthenticatedReportsAuditTrailRoute
  AuthenticatedReportsConsolidatedStatementsRoute: typeof AuthenticatedReportsConsolidatedStatementsRoute
  AuthenticatedReportsIcReconciliationRoute: typeof AuthenticatedReportsIcReconciliationRoute
  AuthenticatedReportsTrialBalanceRoute: typeof AuthenticatedReportsTrialBalanceRoute
  AuthenticatedRulesBalanceCarryForwardRoute: typeof AuthenticatedRulesBalanceCarryForwardRoute
  AuthenticatedRulesConsolidationOfInvestmentsRoute: typeof AuthenticatedRulesConsolidationOfInvestmentsRoute
  AuthenticatedRulesCurrencyTranslationRoute: typeof AuthenticatedRulesCurrencyTranslationRoute
  AuthenticatedRulesIcEliminationRoute: typeof AuthenticatedRulesIcEliminationRoute
  AuthenticatedRulesNetIncomeRoute: typeof AuthenticatedRulesNetIncomeRoute
  AuthenticatedSetupConsGroupsRoute: typeof AuthenticatedSetupConsGroupsRoute
  AuthenticatedSetupDataModelRoute: typeof AuthenticatedSetupDataModelRoute
  AuthenticatedSetupDimensionsRoute: typeof AuthenticatedSetupDimensionsRoute
  AuthenticatedSetupFxRatesRoute: typeof AuthenticatedSetupFxRatesRoute
  AuthenticatedSetupHierarchiesRoute: typeof AuthenticatedSetupHierarchiesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDataBrowserRoute: AuthenticatedDataBrowserRoute,
  AuthenticatedDataJournalsRoute: AuthenticatedDataJournalsRoute,
  AuthenticatedDataUploadRoute: AuthenticatedDataUploadRoute,
  AuthenticatedProcessMonitorRoute: AuthenticatedProcessMonitorRoute,
  AuthenticatedProcessTaskLogRoute: AuthenticatedProcessTaskLogRoute,
  AuthenticatedProcessWorkflowTemplatesRoute:
    AuthenticatedProcessWorkflowTemplatesRoute,
  AuthenticatedReportsAuditTrailRoute: AuthenticatedReportsAuditTrailRoute,
  AuthenticatedReportsConsolidatedStatementsRoute:
    AuthenticatedReportsConsolidatedStatementsRoute,
  AuthenticatedReportsIcReconciliationRoute:
    AuthenticatedReportsIcReconciliationRoute,
  AuthenticatedReportsTrialBalanceRoute: AuthenticatedReportsTrialBalanceRoute,
  AuthenticatedRulesBalanceCarryForwardRoute:
    AuthenticatedRulesBalanceCarryForwardRoute,
  AuthenticatedRulesConsolidationOfInvestmentsRoute:
    AuthenticatedRulesConsolidationOfInvestmentsRoute,
  AuthenticatedRulesCurrencyTranslationRoute:
    AuthenticatedRulesCurrencyTranslationRoute,
  AuthenticatedRulesIcEliminationRoute: AuthenticatedRulesIcEliminationRoute,
  AuthenticatedRulesNetIncomeRoute: AuthenticatedRulesNetIncomeRoute,
  AuthenticatedSetupConsGroupsRoute: AuthenticatedSetupConsGroupsRoute,
  AuthenticatedSetupDataModelRoute: AuthenticatedSetupDataModelRoute,
  AuthenticatedSetupDimensionsRoute: AuthenticatedSetupDimensionsRoute,
  AuthenticatedSetupFxRatesRoute: AuthenticatedSetupFxRatesRoute,
  AuthenticatedSetupHierarchiesRoute: AuthenticatedSetupHierarchiesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
